import type { RegistryObject, RoadmapTask, Project, NotificationItem } from '@/types';

export const DEMO_OBJECTS: RegistryObject[] = [
  {
    id: 'obj-001',
    name: 'Школа № 12 на 1224 места',
    type: 'Строительство',
    industry: 'Образование',
    address: 'г. Одинцово, мкр. Голицыно, ул. Заводская, 4',
    coords: [55.6163, 36.9851],
    source: 'external',
    incomingDate: '2026-07-15',
    description: 'Объект поступил из ИС «Геопортал Московской области» после анализа территории и установления координат. Предполагается строительство новой школы в микрорайоне активной жилой застройки.',
    status: 'new',
    checks: [],
  },
  {
    id: 'obj-002',
    name: 'Детский сад «Солнышко» на 280 мест',
    type: 'Строительство',
    industry: 'Образование',
    address: 'г. Химки, мкр. Подрезково, ул. Центральная, 12',
    coords: [55.9412, 37.3499],
    source: 'external',
    incomingDate: '2026-07-14',
    description: 'Участок выявлен по результатам геоанализа обеспеченности дошкольными учреждениями. Требуется рассмотрение целесообразности строительства.',
    status: 'new',
    checks: [],
  },
  {
    id: 'obj-003',
    name: 'Поликлиника № 3 — капитальный ремонт',
    type: 'Ремонт',
    industry: 'Здравоохранение',
    address: 'г. Балашиха, ул. Советская, 8',
    coords: [55.8094, 37.9581],
    source: 'external',
    incomingDate: '2026-07-03',
    description: 'Здание 1974 г.п., износ инженерных систем более 60%. Поступило обращение ведомства здравоохранения о необходимости капитального ремонта.',
    status: 'checking',
    checks: [
      {
        id: 'chk-031', vedomstvo: 'Минздрав МО', assignee: 'Сидорова Е.М.', status: 'done',
        visitDate: '2026-07-08', doneDate: '2026-07-10',
        photos: [{ id: 'ph-1', label: 'Фасад здания' }, { id: 'ph-2', label: 'Тепловой узел' }],
        comment: 'Объект осмотрен. Состояние инженерных сетей неудовлетворительное, требуется замена. Работы необходимы.',
        verdict: 'agree',
      },
      { id: 'chk-032', vedomstvo: 'Минстрой МО', assignee: 'Волков П.Н.', status: 'in_progress', visitDate: '2026-07-18', photos: [] },
      { id: 'chk-033', vedomstvo: 'Комархитектура МО', assignee: 'Медведева Н.Н.', status: 'pending', photos: [] },
    ],
  },
  {
    id: 'obj-004',
    name: 'Школа № 5 — капитальный ремонт',
    type: 'Ремонт',
    industry: 'Образование',
    address: 'г. Подольск, ул. Кирова, 21',
    coords: [55.4242, 37.5547],
    source: 'external',
    incomingDate: '2026-05-20',
    description: 'Капитальный ремонт здания школы с заменой инженерных систем, кровли и фасада. После ремонта планируется перевод учащихся школы № 7.',
    status: 'approved',
    projectId: 'prj-1',
    checks: [
      { id: 'chk-041', vedomstvo: 'Минобразования МО', assignee: 'Петров И.С.', status: 'done', visitDate: '2026-06-02', doneDate: '2026-06-05', photos: [{ id: 'ph-3', label: 'Актовый зал' }], comment: 'Работы необходимы, школа перегружена.', verdict: 'agree' },
      { id: 'chk-042', vedomstvo: 'Минстрой МО', assignee: 'Волков П.Н.', status: 'done', visitDate: '2026-06-04', doneDate: '2026-06-09', photos: [{ id: 'ph-4', label: 'Кровля' }, { id: 'ph-5', label: 'Фасад' }], comment: 'Подтверждена необходимость замены кровли и инженерных систем.', verdict: 'agree' },
      { id: 'chk-043', vedomstvo: 'Минимущество МО', assignee: 'Лебедева О.В.', status: 'done', visitDate: '2026-06-10', doneDate: '2026-06-12', photos: [], comment: 'Замечаний по правоустанавливающим документам нет.', verdict: 'agree' },
    ],
    conclusion: {
      result: 'approved',
      text: 'По итогам проверок всех ведомств (3 из 3 — «согласовано») проведение работ по объекту признано целесообразным.',
      date: '2026-06-12',
    },
  },
  {
    id: 'obj-005',
    name: 'Школа № 7 — передача здания после ремонта школы № 5',
    type: 'Реконструкция',
    industry: 'Образование',
    address: 'г. Подольск, ул. Фёдорова, 14',
    coords: [55.4312, 37.5419],
    source: 'external',
    incomingDate: '2026-05-20',
    description: 'После завершения ремонта школы № 5 учащиеся переводятся в отремонтированное здание, здание школы № 7 передаётся на баланс Минимущества МО.',
    status: 'approved',
    projectId: 'prj-1',
    checks: [
      { id: 'chk-051', vedomstvo: 'Минобразования МО', assignee: 'Петров И.С.', status: 'done', visitDate: '2026-06-03', doneDate: '2026-06-06', photos: [{ id: 'ph-6', label: 'Здание школы' }], comment: 'Перевод учащихся возможен с начала учебного года.', verdict: 'agree' },
      { id: 'chk-052', vedomstvo: 'Минимущество МО', assignee: 'Лебедева О.В.', status: 'done', visitDate: '2026-06-11', doneDate: '2026-06-14', photos: [], comment: 'Готовы принять здание на баланс после перевода учащихся.', verdict: 'agree' },
    ],
    conclusion: {
      result: 'approved',
      text: 'По итогам проверок всех ведомств (2 из 2 — «согласовано») проведение работ по объекту признано целесообразным.',
      date: '2026-06-14',
    },
  },
  {
    id: 'obj-006',
    name: 'Стадион «Труд» — реконструкция',
    type: 'Реконструкция',
    industry: 'Спорт',
    address: 'г. Серпухов, ул. Ворошилова, 135',
    coords: [54.9226, 37.4033],
    source: 'external',
    incomingDate: '2026-06-01',
    description: 'Реконструкция муниципального стадиона с заменой покрытия и трибун.',
    status: 'rejected',
    checks: [
      { id: 'chk-061', vedomstvo: 'Минспорт МО', assignee: 'Титов С.П.', status: 'done', visitDate: '2026-06-10', doneDate: '2026-06-12', photos: [{ id: 'ph-7', label: 'Поле стадиона' }], comment: 'Реконструкция необходима, покрытие изношено.', verdict: 'agree' },
      { id: 'chk-062', vedomstvo: 'Минимущество МО', assignee: 'Лебедева О.В.', status: 'done', visitDate: '2026-06-15', doneDate: '2026-06-18', photos: [], comment: 'Территория вовлечена в проект комплексного развития, работы в текущей редакции преждевременны.', verdict: 'reject' },
    ],
    conclusion: {
      result: 'rejected',
      text: 'Есть отклонившие ведомства (1 из 2). Проведение работ по объекту в текущей редакции не согласовано. Требуется доработка предложения.',
      date: '2026-06-18',
    },
  },
  {
    id: 'obj-007',
    name: 'ФАП в д. Никольское',
    type: 'Строительство',
    industry: 'Здравоохранение',
    address: 'Рузский г.о., д. Никольское, ул. Луговая, 3',
    coords: [55.6481, 36.2817],
    source: 'external',
    incomingDate: '2026-07-16',
    description: 'Строительство фельдшерско-акушерского пункта по итогам анализа доступности медицинской помощи в сельских поселениях.',
    status: 'new',
    checks: [],
  },
  {
    id: 'obj-008',
    name: 'Дом культуры «Октябрь» — капитальный ремонт',
    type: 'Ремонт',
    industry: 'Культура',
    address: 'г. Дмитров, пл. Советская, 1',
    coords: [56.3449, 37.5204],
    source: 'external',
    incomingDate: '2026-07-06',
    description: 'Здание является объектом культурного наследия регионального значения. Требуется капитальный ремонт с реставрационными работами.',
    status: 'checking',
    checks: [
      { id: 'chk-081', vedomstvo: 'Минкультуры МО', assignee: 'Зайцева Л.Д.', status: 'done', visitDate: '2026-07-10', doneDate: '2026-07-13', photos: [{ id: 'ph-8', label: 'Фасад ДК' }, { id: 'ph-9', label: 'Лепнина зала' }], comment: 'Работы необходимы, требуется реставрационный проект.', verdict: 'agree' },
      { id: 'chk-082', vedomstvo: 'Комархитектура МО', assignee: 'Медведева Н.Н.', status: 'pending', photos: [] },
    ],
  },
  {
    id: 'obj-009',
    name: 'Школа № 3 — строительство пристройки',
    type: 'Строительство',
    industry: 'Образование',
    address: 'г. Электросталь, ул. Победы, 17',
    coords: [55.7896, 38.4466],
    source: 'manual',
    incomingDate: '2026-07-12',
    description: 'Объект добавлен вручную по обращению администрации городского округа: требуется пристройка на 300 мест в связи с перегрузкой школы.',
    status: 'new',
    checks: [],
  },
  {
    id: 'obj-010',
    name: 'Городская больница — ремонт терапевтического корпуса',
    type: 'Ремонт',
    industry: 'Здравоохранение',
    address: 'г. Коломна, ул. Октябрьской революции, 218',
    coords: [55.0794, 38.7783],
    source: 'external',
    incomingDate: '2026-04-15',
    description: 'Капитальный ремонт терапевтического корпуса с переустройством палат и заменой инженерных систем.',
    status: 'approved',
    checks: [
      { id: 'chk-101', vedomstvo: 'Минздрав МО', assignee: 'Сидорова Е.М.', status: 'done', visitDate: '2026-04-22', doneDate: '2026-04-25', photos: [{ id: 'ph-10', label: 'Палатное отделение' }], comment: 'Ремонт необходим.', verdict: 'agree' },
      { id: 'chk-102', vedomstvo: 'Минстрой МО', assignee: 'Волков П.Н.', status: 'done', visitDate: '2026-04-24', doneDate: '2026-04-28', photos: [], comment: 'Техническое состояние подтверждает необходимость работ.', verdict: 'agree' },
    ],
    conclusion: {
      result: 'approved',
      text: 'По итогам проверок всех ведомств (2 из 2 — «согласовано») проведение работ по объекту признано целесообразным.',
      date: '2026-04-28',
    },
  },
];

export const DEMO_TASKS: RoadmapTask[] = [
  // Школа № 5
  { id: 't-01', objectId: 'obj-004', title: 'Разработка и экспертиза проектной документации', assignee: 'Волков П.Н.', vedomstvo: 'Минстрой МО', planStart: '2026-03-01', planEnd: '2026-05-15', factStart: '2026-03-02', factEnd: '2026-05-20', status: 'done' },
  { id: 't-02', objectId: 'obj-004', title: 'Конкурентные процедуры и контрактация', assignee: 'Смирнова А.В.', vedomstvo: 'Минстрой МО', planStart: '2026-05-16', planEnd: '2026-06-20', factStart: '2026-05-21', factEnd: '2026-06-25', status: 'done' },
  { id: 't-03', objectId: 'obj-004', title: 'Ремонтно-строительные работы', assignee: 'Волков П.Н.', vedomstvo: 'Минстрой МО', planStart: '2026-07-01', planEnd: '2026-08-20', factStart: '2026-07-03', status: 'in_progress' },
  { id: 't-04', objectId: 'obj-004', title: 'Оснащение и меблировка', assignee: 'Петров И.С.', vedomstvo: 'Минобразования МО', planStart: '2026-08-10', planEnd: '2026-08-25', status: 'not_started' },
  { id: 't-05', objectId: 'obj-004', title: 'Ввод объекта в эксплуатацию', assignee: 'Смирнова А.В.', vedomstvo: 'Минстрой МО', planStart: '2026-08-26', planEnd: '2026-08-31', status: 'not_started' },
  // Школа № 7
  { id: 't-06', objectId: 'obj-005', title: 'Согласование схемы перевода учащихся', assignee: 'Петров И.С.', vedomstvo: 'Минобразования МО', planStart: '2026-06-01', planEnd: '2026-06-30', factStart: '2026-06-05', status: 'in_progress' },
  { id: 't-07', objectId: 'obj-005', title: 'Перевод учащихся в школу № 5', assignee: 'Петров И.С.', vedomstvo: 'Минобразования МО', planStart: '2026-08-26', planEnd: '2026-09-01', status: 'not_started' },
  { id: 't-08', objectId: 'obj-005', title: 'Инвентаризация имущества школы № 7', assignee: 'Лебедева О.В.', vedomstvo: 'Минимущество МО', planStart: '2026-07-20', planEnd: '2026-08-15', status: 'not_started' },
  { id: 't-09', objectId: 'obj-005', title: 'Передача здания на баланс Минимущества МО', assignee: 'Лебедева О.В.', vedomstvo: 'Минимущество МО', planStart: '2026-09-05', planEnd: '2026-09-30', status: 'not_started' },
  // Больница Коломна
  { id: 't-10', objectId: 'obj-010', title: 'Проектная документация и экспертиза', assignee: 'Сидорова Е.М.', vedomstvo: 'Минздрав МО', planStart: '2026-04-01', planEnd: '2026-05-30', factStart: '2026-04-03', factEnd: '2026-06-05', status: 'done' },
  { id: 't-11', objectId: 'obj-010', title: 'Торги и заключение контракта', assignee: 'Смирнова А.В.', vedomstvo: 'Минстрой МО', planStart: '2026-06-01', planEnd: '2026-07-10', factStart: '2026-06-02', status: 'in_progress' },
  { id: 't-12', objectId: 'obj-010', title: 'Ремонтные работы, 1 этап', assignee: 'Волков П.Н.', vedomstvo: 'Минстрой МО', planStart: '2026-07-15', planEnd: '2026-10-30', factStart: '2026-07-15', status: 'in_progress' },
];

export const DEMO_PROJECTS: Project[] = [
  {
    id: 'prj-1',
    name: 'Реорганизация школьной сети г. Подольска',
    description: 'После завершения капитального ремонта школы № 5 учащиеся школы № 7 переводятся в отремонтированное здание; здание школы № 7 передаётся на баланс Минимущества Московской области.',
    objectIds: ['obj-004', 'obj-005'],
    createdDate: '2026-06-25',
  },
];

export const DEMO_NOTIFICATIONS: NotificationItem[] = [
  { id: 'n-1', date: '2026-07-16T09:12', text: 'Поступил новый объект из ИС «Геопортал МО»: ФАП в д. Никольское', kind: 'object', roles: ['coordinator'], read: false, objectId: 'obj-007' },
  { id: 'n-2', date: '2026-07-15T11:40', text: 'Поступил новый объект из ИС «Геопортал МО»: Школа № 12 на 1224 места', kind: 'object', roles: ['coordinator'], read: false, objectId: 'obj-001' },
  { id: 'n-3', date: '2026-07-13T15:02', text: 'Минкультуры МО завершило проверку по объекту «Дом культуры „Октябрь“»: согласовано', kind: 'check', roles: ['coordinator'], read: true, objectId: 'obj-008' },
  { id: 'n-4', date: '2026-07-10T10:25', text: 'Минздрав МО завершило проверку по объекту «Поликлиника № 3»: согласовано', kind: 'check', roles: ['coordinator'], read: true, objectId: 'obj-003' },
  { id: 'n-5', date: '2026-07-08T08:30', text: 'Назначена проверка по объекту «Поликлиника № 3 — капитальный ремонт»', kind: 'check', roles: ['inspector'], read: false, objectId: 'obj-003' },
  { id: 'n-6', date: '2026-07-01T09:00', text: 'Задача «Согласование схемы перевода учащихся» просрочена (план: 30.06.2026)', kind: 'task', roles: ['inspector', 'manager'], read: false },
  { id: 'n-7', date: '2026-06-30T17:45', text: 'Сформировано итоговое заключение по объекту «Школа № 5»: работы согласованы', kind: 'conclusion', roles: ['manager', 'coordinator'], read: true, objectId: 'obj-004' },
  { id: 'n-8', date: '2026-06-18T12:10', text: 'Итоговое заключение по объекту «Стадион „Труд“»: работы отклонены', kind: 'conclusion', roles: ['manager', 'coordinator'], read: true, objectId: 'obj-006' },
];
