import type { RegistryObject, RoadmapTask, Project, NotificationItem } from '@/types';

export const DEMO_OBJECTS: RegistryObject[] = [
  {
    id: 'obj-001',
    name: 'Школа № 12 на 1224 места',
    type: 'Строительство',
    industry: 'Образование',
    category: 'Школа',
    district: 'Одинцовский г.о.',
    address: 'г. Одинцово, мкр. Голицыно, ул. Заводская, 4',
    coords: [55.6163, 36.9851],
    source: 'external',
    incomingDate: '2026-07-15',
    description: 'Объект поступил из ИС «Геопортал Московской области» после анализа территории и установления координат. Предполагается строительство новой школы в микрорайоне активной жилой застройки.',
    status: 'new',
    checks: [],
  },
  {
    id: 'obj-002',
    name: 'Детский сад «Солнышко» на 280 мест',
    type: 'Строительство',
    industry: 'Образование',
    category: 'Детский сад',
    district: 'г.о. Химки',
    address: 'г. Химки, мкр. Подрезково, ул. Центральная, 12',
    coords: [55.9412, 37.3499],
    source: 'external',
    incomingDate: '2026-07-14',
    description: 'Участок выявлен по результатам геоанализа обеспеченности дошкольными учреждениями. Требуется рассмотрение целесообразности строительства.',
    status: 'new',
    checks: [],
  },
  {
    id: 'obj-003',
    name: 'Поликлиника № 3 — капитальный ремонт',
    type: 'Ремонт',
    industry: 'Здравоохранение',
    category: 'Поликлиника',
    district: 'г.о. Балашиха',
    address: 'г. Балашиха, ул. Советская, 8',
    coords: [55.8094, 37.9581],
    source: 'external',
    incomingDate: '2026-07-03',
    description: 'Здание 1974 г.п., износ инженерных систем более 60%. Поступило обращение ведомства здравоохранения о необходимости капитального ремонта.',
    status: 'checking',
    checks: [
      {
        id: 'chk-031', vedomstvo: 'Минздрав МО', assignee: 'Сидорова Е.М.', status: 'done',
        assignedDate: '2026-07-04', visitDate: '2026-07-08', doneDate: '2026-07-10',
        photos: [{ id: 'ph-1', label: 'Фасад здания' }, { id: 'ph-2', label: 'Тепловой узел' }],
        comment: 'Объект осмотрен. Состояние инженерных сетей неудовлетворительное, требуется замена. Работы необходимы.',
        verdict: 'agree',
      },
      { id: 'chk-032', vedomstvo: 'Минстрой МО', assignee: 'Волков П.Н.', status: 'in_progress', assignedDate: '2026-07-04', visitDate: '2026-07-18', photos: [] },
      { id: 'chk-033', vedomstvo: 'Комархитектура МО', assignee: 'Медведева Н.Н.', status: 'pending', assignedDate: '2026-07-04', photos: [] },
    ],
  },
  {
    id: 'obj-004',
    name: 'Школа № 5 — капитальный ремонт',
    type: 'Ремонт',
    industry: 'Образование',
    category: 'Школа',
    district: 'г.о. Подольск',
    address: 'г. Подольск, ул. Кирова, 21',
    coords: [55.4242, 37.5547],
    source: 'external',
    incomingDate: '2026-05-20',
    description: 'Капитальный ремонт здания школы с заменой инженерных систем, кровли и фасада. После ремонта планируется перевод учащихся школы № 7.',
    status: 'approved',
    projectId: 'prj-1',
    checks: [
      { id: 'chk-041', vedomstvo: 'Минобразования МО', assignee: 'Петров И.С.', status: 'done', assignedDate: '2026-05-21', visitDate: '2026-06-02', doneDate: '2026-06-05', photos: [{ id: 'ph-3', label: 'Актовый зал' }], comment: 'Работы необходимы, школа перегружена.', verdict: 'agree' },
      { id: 'chk-042', vedomstvo: 'Минстрой МО', assignee: 'Волков П.Н.', status: 'done', assignedDate: '2026-05-21', visitDate: '2026-06-04', doneDate: '2026-06-09', photos: [{ id: 'ph-4', label: 'Кровля' }, { id: 'ph-5', label: 'Фасад' }], comment: 'Подтверждена необходимость замены кровли и инженерных систем.', verdict: 'agree' },
      { id: 'chk-043', vedomstvo: 'Минимущество МО', assignee: 'Лебедева О.В.', status: 'done', assignedDate: '2026-05-21', visitDate: '2026-06-10', doneDate: '2026-06-12', photos: [], comment: 'Замечаний по правоустанавливающим документам нет.', verdict: 'agree' },
    ],
    conclusion: {
      result: 'approved',
      text: 'По итогам проверок всех ведомств (3 из 3 — «согласовано») проведение работ по объекту признано целесообразным.',
      date: '2026-06-12',
    },
    decision: { kind: 'capital', date: '2026-06-16', planFunding: 180, usedFunding: 64, source: 'Бюджет Московской области' },
  },
  {
    id: 'obj-005',
    name: 'Школа № 7 — передача здания после ремонта школы № 5',
    type: 'Реконструкция',
    industry: 'Образование',
    category: 'Школа',
    district: 'г.о. Подольск',
    address: 'г. Подольск, ул. Фёдорова, 14',
    coords: [55.4312, 37.5419],
    source: 'external',
    incomingDate: '2026-05-20',
    description: 'После завершения ремонта школы № 5 учащиеся переводятся в отремонтированное здание, здание школы № 7 передаётся на баланс Минимущества МО.',
    status: 'approved',
    projectId: 'prj-1',
    checks: [
      { id: 'chk-051', vedomstvo: 'Минобразования МО', assignee: 'Петров И.С.', status: 'done', assignedDate: '2026-05-21', visitDate: '2026-06-03', doneDate: '2026-06-06', photos: [{ id: 'ph-6', label: 'Здание школы' }], comment: 'Перевод учащихся возможен с начала учебного года.', verdict: 'agree' },
      { id: 'chk-052', vedomstvo: 'Минимущество МО', assignee: 'Лебедева О.В.', status: 'done', assignedDate: '2026-05-21', visitDate: '2026-06-11', doneDate: '2026-06-14', photos: [], comment: 'Готовы принять здание на баланс после перевода учащихся.', verdict: 'agree' },
    ],
    conclusion: {
      result: 'approved',
      text: 'По итогам проверок всех ведомств (2 из 2 — «согласовано») проведение работ по объекту признано целесообразным.',
      date: '2026-06-14',
    },
    decision: { kind: 'transfer', date: '2026-06-19', planFunding: 14, usedFunding: 2, source: 'Муниципальный бюджет' },
  },
  {
    id: 'obj-006',
    name: 'Стадион «Труд» — реконструкция',
    type: 'Реконструкция',
    industry: 'Спорт',
    category: 'Стадион',
    district: 'г.о. Серпухов',
    address: 'г. Серпухов, ул. Ворошилова, 135',
    coords: [54.9226, 37.4033],
    source: 'external',
    incomingDate: '2026-06-01',
    description: 'Реконструкция муниципального стадиона с заменой покрытия и трибун.',
    status: 'rejected',
    checks: [
      { id: 'chk-061', vedomstvo: 'Минспорт МО', assignee: 'Титов С.П.', status: 'done', assignedDate: '2026-06-03', visitDate: '2026-06-10', doneDate: '2026-06-12', photos: [{ id: 'ph-7', label: 'Поле стадиона' }], comment: 'Реконструкция необходима, покрытие изношено.', verdict: 'agree' },
      { id: 'chk-062', vedomstvo: 'Минимущество МО', assignee: 'Лебедева О.В.', status: 'done', assignedDate: '2026-06-03', visitDate: '2026-06-15', doneDate: '2026-06-18', photos: [], comment: 'Территория вовлечена в проект комплексного развития, работы в текущей редакции преждевременны.', verdict: 'reject' },
    ],
    conclusion: {
      result: 'rejected',
      text: 'Есть отклонившие ведомства (1 из 2). Проведение работ по объекту в текущей редакции не согласовано. Требуется доработка предложения.',
      date: '2026-06-18',
    },
    decision: { kind: 'demolition', date: '2026-06-25', planFunding: 45, usedFunding: 0, source: 'Муниципальный бюджет' },
  },
  {
    id: 'obj-007',
    name: 'ФАП в д. Никольское',
    type: 'Строительство',
    industry: 'Здравоохранение',
    category: 'ФАП',
    district: 'Рузский г.о.',
    address: 'Рузский г.о., д. Никольское, ул. Луговая, 3',
    coords: [55.6481, 36.2817],
    source: 'external',
    incomingDate: '2026-07-16',
    description: 'Строительство фельдшерско-акушерского пункта по итогам анализа доступности медицинской помощи в сельских поселениях.',
    status: 'new',
    checks: [],
  },
  {
    id: 'obj-008',
    name: 'Дом культуры «Октябрь» — капитальный ремонт',
    type: 'Ремонт',
    industry: 'Культура',
    category: 'Дом культуры',
    district: 'Дмитровский г.о.',
    address: 'г. Дмитров, пл. Советская, 1',
    coords: [56.3449, 37.5204],
    source: 'external',
    incomingDate: '2026-07-06',
    description: 'Здание является объектом культурного наследия регионального значения. Требуется капитальный ремонт с реставрационными работами.',
    status: 'checking',
    checks: [
      { id: 'chk-081', vedomstvo: 'Минкультуры МО', assignee: 'Зайцева Л.Д.', status: 'done', assignedDate: '2026-07-07', visitDate: '2026-07-10', doneDate: '2026-07-13', photos: [{ id: 'ph-8', label: 'Фасад ДК' }, { id: 'ph-9', label: 'Лепнина зала' }], comment: 'Работы необходимы, требуется реставрационный проект.', verdict: 'agree' },
      { id: 'chk-082', vedomstvo: 'Комархитектура МО', assignee: 'Медведева Н.Н.', status: 'pending', assignedDate: '2026-07-07', photos: [] },
    ],
  },
  {
    id: 'obj-009',
    name: 'Школа № 3 — строительство пристройки',
    type: 'Строительство',
    industry: 'Образование',
    category: 'Школа',
    district: 'г.о. Электросталь',
    address: 'г. Электросталь, ул. Победы, 17',
    coords: [55.7896, 38.4466],
    source: 'manual',
    incomingDate: '2026-07-12',
    description: 'Объект добавлен вручную по обращению администрации городского округа: требуется пристройка на 300 мест в связи с перегрузкой школы.',
    status: 'new',
    checks: [],
  },
  {
    id: 'obj-010',
    name: 'Городская больница — ремонт терапевтического корпуса',
    type: 'Ремонт',
    industry: 'Здравоохранение',
    category: 'Больница',
    district: 'г.о. Коломна',
    address: 'г. Коломна, ул. Октябрьской революции, 218',
    coords: [55.0794, 38.7783],
    source: 'external',
    incomingDate: '2026-04-15',
    description: 'Капитальный ремонт терапевтического корпуса с переустройством палат и заменой инженерных систем.',
    status: 'approved',
    checks: [
      { id: 'chk-101', vedomstvo: 'Минздрав МО', assignee: 'Сидорова Е.М.', status: 'done', assignedDate: '2026-04-16', visitDate: '2026-04-22', doneDate: '2026-04-25', photos: [{ id: 'ph-10', label: 'Палатное отделение' }], comment: 'Ремонт необходим.', verdict: 'agree' },
      { id: 'chk-102', vedomstvo: 'Минстрой МО', assignee: 'Волков П.Н.', status: 'done', assignedDate: '2026-04-16', visitDate: '2026-04-24', doneDate: '2026-04-28', photos: [], comment: 'Техническое состояние подтверждает необходимость работ.', verdict: 'agree' },
    ],
    conclusion: {
      result: 'approved',
      text: 'По итогам проверок всех ведомств (2 из 2 — «согласовано») проведение работ по объекту признано целесообразным.',
      date: '2026-04-28',
    },
    decision: { kind: 'current', date: '2026-05-04', planFunding: 95, usedFunding: 71, source: 'Бюджет Московской области' },
  },
  {
    id: 'obj-011',
    name: 'Школа № 2 — ремонт спортивного зала',
    type: 'Ремонт',
    industry: 'Образование',
    category: 'Школа',
    district: 'Клинский г.о.',
    address: 'г. Клин, ул. Литейная, 5',
    coords: [56.3317, 36.7287],
    source: 'external',
    incomingDate: '2026-02-10',
    description: 'Ремонт спортивного зала с заменой покрытия и вентиляции по итогам обследования.',
    status: 'approved',
    checks: [
      { id: 'chk-111', vedomstvo: 'Минобразования МО', assignee: 'Петров И.С.', status: 'done', assignedDate: '2026-02-12', visitDate: '2026-02-25', doneDate: '2026-03-02', photos: [{ id: 'ph-11', label: 'Спортзал' }], comment: 'Работы необходимы.', verdict: 'agree' },
      { id: 'chk-112', vedomstvo: 'Минстрой МО', assignee: 'Волков П.Н.', status: 'done', assignedDate: '2026-02-12', visitDate: '2026-02-27', doneDate: '2026-03-04', photos: [], comment: 'Объём работ подтверждён.', verdict: 'agree' },
    ],
    conclusion: {
      result: 'approved',
      text: 'По итогам проверок всех ведомств (2 из 2 — «согласовано») проведение работ по объекту признано целесообразным.',
      date: '2026-03-05',
    },
    decision: { kind: 'current', date: '2026-03-10', planFunding: 42, usedFunding: 42, source: 'Бюджет Московской области' },
  },
  {
    id: 'obj-012',
    name: 'Поликлиника № 1 — строительство пристройки',
    type: 'Строительство',
    industry: 'Здравоохранение',
    category: 'Поликлиника',
    district: 'г.о. Мытищи',
    address: 'г. Мытищи, ул. Комарова, 2',
    coords: [55.9108, 37.7363],
    source: 'external',
    incomingDate: '2026-03-02',
    description: 'Строительство пристройки под процедурные кабинеты в связи с ростом прикреплённого населения.',
    status: 'approved',
    checks: [
      { id: 'chk-121', vedomstvo: 'Минздрав МО', assignee: 'Сидорова Е.М.', status: 'done', assignedDate: '2026-03-04', visitDate: '2026-03-15', doneDate: '2026-03-28', photos: [{ id: 'ph-12', label: 'Участок пристройки' }], comment: 'Потребность подтверждена.', verdict: 'agree' },
      { id: 'chk-122', vedomstvo: 'Комархитектура МО', assignee: 'Медведева Н.Н.', status: 'done', assignedDate: '2026-03-04', visitDate: '2026-03-18', doneDate: '2026-04-01', photos: [], comment: 'Градостроительное решение возможно.', verdict: 'agree' },
    ],
    conclusion: {
      result: 'approved',
      text: 'По итогам проверок всех ведомств (2 из 2 — «согласовано») проведение работ по объекту признано целесообразным.',
      date: '2026-04-02',
    },
    decision: { kind: 'construction', date: '2026-04-08', planFunding: 320, usedFunding: 118, source: 'Федеральный и областной бюджеты' },
  },
  {
    id: 'obj-013',
    name: 'Детский сад № 8 — капитальный ремонт',
    type: 'Ремонт',
    industry: 'Образование',
    category: 'Детский сад',
    district: 'Волоколамский г.о.',
    address: 'г. Волоколамск, ул. Панфилова, 11',
    coords: [56.0336, 35.9572],
    source: 'external',
    incomingDate: '2026-03-15',
    description: 'Капитальный ремонт здания детского сада 1911 г.п.',
    status: 'rejected',
    checks: [
      { id: 'chk-131', vedomstvo: 'Минобразования МО', assignee: 'Петров И.С.', status: 'done', assignedDate: '2026-03-18', visitDate: '2026-03-30', doneDate: '2026-04-05', photos: [], comment: 'Ремонт необходим, учреждение перегружено.', verdict: 'agree' },
      { id: 'chk-132', vedomstvo: 'Комархитектура МО', assignee: 'Медведева Н.Н.', status: 'done', assignedDate: '2026-03-18', visitDate: '2026-04-10', doneDate: '2026-04-18', photos: [], comment: 'Здание — выявленный объект культурного наследия. Требуется реставрационный проект, типовой ремонт невозможен.', verdict: 'reject' },
    ],
    conclusion: {
      result: 'rejected',
      text: 'Есть отклонившие ведомства (1 из 2). Проведение работ по объекту в текущей редакции не согласовано. Требуется доработка предложения.',
      date: '2026-04-20',
    },
    decision: { kind: 'transfer', date: '2026-04-27', planFunding: 6, usedFunding: 1, source: 'Муниципальный бюджет' },
  },
  {
    id: 'obj-014',
    name: 'ФОК «Лидер» — строительство',
    type: 'Строительство',
    industry: 'Спорт',
    category: 'ФОК',
    district: 'г.о. Красногорск',
    address: 'г. Красногорск, бульвар Строителей, 3',
    coords: [55.8315, 37.3296],
    source: 'external',
    incomingDate: '2026-04-05',
    description: 'Строительство физкультурно-оздоровительного комплекса с бассейном в микрорайоне новой застройки.',
    status: 'approved',
    checks: [
      { id: 'chk-141', vedomstvo: 'Минспорт МО', assignee: 'Титов С.П.', status: 'done', assignedDate: '2026-04-07', visitDate: '2026-04-20', doneDate: '2026-04-25', photos: [], comment: 'Потребность подтверждена.', verdict: 'agree' },
      { id: 'chk-142', vedomstvo: 'Минимущество МО', assignee: 'Лебедева О.В.', status: 'done', assignedDate: '2026-04-07', visitDate: '2026-04-28', doneDate: '2026-05-08', photos: [], comment: 'Участок свободен, обременений нет.', verdict: 'agree' },
    ],
    conclusion: {
      result: 'approved',
      text: 'По итогам проверок всех ведомств (2 из 2 — «согласовано») проведение работ по объекту признано целесообразным.',
      date: '2026-05-10',
    },
    decision: { kind: 'construction', date: '2026-05-15', planFunding: 850, usedFunding: 246, source: 'Бюджет Московской области' },
  },
  {
    id: 'obj-015',
    name: 'Школа № 9 — капитальный ремонт',
    type: 'Ремонт',
    industry: 'Образование',
    category: 'Школа',
    district: 'Сергиево-Посадский г.о.',
    address: 'г. Сергиев Посад, пр-т Красной Армии, 140',
    coords: [56.3153, 38.136],
    source: 'external',
    incomingDate: '2026-05-11',
    description: 'Капитальный ремонт с заменой оконных блоков и системы отопления.',
    status: 'approved',
    checks: [
      { id: 'chk-151', vedomstvo: 'Минобразования МО', assignee: 'Петров И.С.', status: 'done', assignedDate: '2026-05-13', visitDate: '2026-05-25', doneDate: '2026-05-30', photos: [], comment: 'Работы необходимы.', verdict: 'agree' },
      { id: 'chk-152', vedomstvo: 'Минстрой МО', assignee: 'Волков П.Н.', status: 'done', assignedDate: '2026-05-13', visitDate: '2026-05-29', doneDate: '2026-06-05', photos: [], comment: 'Техническое состояние подтверждает объём работ.', verdict: 'agree' },
    ],
    conclusion: {
      result: 'approved',
      text: 'По итогам проверок всех ведомств (2 из 2 — «согласовано») проведение работ по объекту признано целесообразным.',
      date: '2026-06-08',
    },
    decision: { kind: 'capital', date: '2026-06-11', planFunding: 210, usedFunding: 28, source: 'Бюджет Московской области' },
  },
  {
    id: 'obj-016',
    name: 'Больница № 2 — ремонт приёмного отделения',
    type: 'Ремонт',
    industry: 'Здравоохранение',
    category: 'Больница',
    district: 'Орехово-Зуевский г.о.',
    address: 'г. Орехово-Зуево, ул. Карла Маркса, 22',
    coords: [55.8067, 38.9618],
    source: 'external',
    incomingDate: '2026-06-02',
    description: 'Ремонт приёмного отделения с переустройством смотровых кабинетов.',
    status: 'checking',
    checks: [
      { id: 'chk-161', vedomstvo: 'Минздрав МО', assignee: 'Сидорова Е.М.', status: 'done', assignedDate: '2026-06-04', visitDate: '2026-06-12', doneDate: '2026-06-15', photos: [], comment: 'Ремонт необходим.', verdict: 'agree' },
      { id: 'chk-162', vedomstvo: 'Минстрой МО', assignee: 'Волков П.Н.', status: 'done', assignedDate: '2026-06-04', visitDate: '2026-06-18', doneDate: '2026-06-22', photos: [], comment: 'Объём работ подтверждён.', verdict: 'agree' },
      { id: 'chk-163', vedomstvo: 'Госстройнадзор МО', assignee: 'Орлова Т.И.', status: 'pending', assignedDate: '2026-06-20', photos: [] },
    ],
  },
  {
    id: 'obj-017',
    name: 'Дом культуры «Родина» — реставрация',
    type: 'Ремонт',
    industry: 'Культура',
    category: 'Дом культуры',
    district: 'Клинский г.о.',
    address: 'г. Клин, ул. Гагарина, 9',
    coords: [56.3425, 36.7241],
    source: 'external',
    incomingDate: '2026-06-12',
    description: 'Реставрация фасада и ремонт зрительного зала.',
    status: 'approved',
    checks: [
      { id: 'chk-171', vedomstvo: 'Минкультуры МО', assignee: 'Зайцева Л.Д.', status: 'done', assignedDate: '2026-06-15', visitDate: '2026-06-22', doneDate: '2026-06-25', photos: [], comment: 'Работы необходимы.', verdict: 'agree' },
      { id: 'chk-172', vedomstvo: 'Комархитектура МО', assignee: 'Медведева Н.Н.', status: 'done', assignedDate: '2026-06-15', visitDate: '2026-06-26', doneDate: '2026-07-01', photos: [], comment: 'Согласовано при условии реставрационного проекта.', verdict: 'agree' },
    ],
    conclusion: {
      result: 'approved',
      text: 'По итогам проверок всех ведомств (2 из 2 — «согласовано») проведение работ по объекту признано целесообразным.',
      date: '2026-07-03',
    },
    decision: { kind: 'capital', date: '2026-07-08', planFunding: 130, usedFunding: 4, source: 'Бюджет Московской области' },
  },
  {
    id: 'obj-018',
    name: 'Школа № 15 на 1500 мест',
    type: 'Строительство',
    industry: 'Образование',
    category: 'Школа',
    district: 'г.о. Мытищи',
    address: 'г. Мытищи, мкр. Ярославский, ул. Сукромка, 21',
    coords: [55.9231, 37.7601],
    source: 'external',
    incomingDate: '2026-06-20',
    description: 'Строительство новой школы в микрорайоне активной жилой застройки.',
    status: 'checking',
    checks: [
      { id: 'chk-181', vedomstvo: 'Минобразования МО', assignee: 'Петров И.С.', status: 'done', assignedDate: '2026-06-23', visitDate: '2026-07-01', doneDate: '2026-07-05', photos: [], comment: 'Строительство необходимо, школы микрорайона перегружены.', verdict: 'agree' },
      { id: 'chk-182', vedomstvo: 'Минимущество МО', assignee: 'Лебедева О.В.', status: 'in_progress', assignedDate: '2026-06-23', visitDate: '2026-07-19', photos: [] },
      { id: 'chk-183', vedomstvo: 'Минтранс МО', assignee: 'Громов А.А.', status: 'pending', assignedDate: '2026-06-23', photos: [] },
    ],
  },
  {
    id: 'obj-019',
    name: 'ФАП в д. Городище',
    type: 'Строительство',
    industry: 'Здравоохранение',
    category: 'ФАП',
    district: 'Волоколамский г.о.',
    address: 'Волоколамский г.о., д. Городище, ул. Полевая, 2',
    coords: [56.0512, 35.8821],
    source: 'external',
    incomingDate: '2026-07-01',
    description: 'Строительство фельдшерско-акушерского пункта по итогам анализа доступности медпомощи.',
    status: 'new',
    checks: [],
  },
  {
    id: 'obj-020',
    name: 'Стадион «Металлург» — ремонт трибун',
    type: 'Ремонт',
    industry: 'Спорт',
    category: 'Стадион',
    district: 'г.о. Электросталь',
    address: 'г. Электросталь, ул. Тевосяна, 30',
    coords: [55.7781, 38.4549],
    source: 'manual',
    incomingDate: '2026-07-08',
    description: 'Объект добавлен вручную по обращению администрации округа: ремонт трибун и беговых дорожек.',
    status: 'new',
    checks: [],
  },
];

export const DEMO_TASKS: RoadmapTask[] = [
  // Школа № 5
  { id: 't-01', objectId: 'obj-004', title: 'Разработка и экспертиза проектной документации', assignee: 'Волков П.Н.', vedomstvo: 'Минстрой МО', planStart: '2026-03-01', planEnd: '2026-05-15', factStart: '2026-03-02', factEnd: '2026-05-20', status: 'done' },
  { id: 't-02', objectId: 'obj-004', title: 'Конкурентные процедуры и контрактация', assignee: 'Смирнова А.В.', vedomstvo: 'Минстрой МО', planStart: '2026-05-16', planEnd: '2026-06-20', factStart: '2026-05-21', factEnd: '2026-06-25', status: 'done' },
  { id: 't-03', objectId: 'obj-004', title: 'Ремонтно-строительные работы', assignee: 'Волков П.Н.', vedomstvo: 'Минстрой МО', planStart: '2026-07-01', planEnd: '2026-08-20', factStart: '2026-07-03', status: 'in_progress' },
  { id: 't-04', objectId: 'obj-004', title: 'Оснащение и меблировка', assignee: 'Петров И.С.', vedomstvo: 'Минобразования МО', planStart: '2026-08-10', planEnd: '2026-08-25', status: 'not_started' },
  { id: 't-05', objectId: 'obj-004', title: 'Ввод объекта в эксплуатацию', assignee: 'Смирнова А.В.', vedomstvo: 'Минстрой МО', planStart: '2026-08-26', planEnd: '2026-08-31', status: 'not_started' },
  // Школа № 7
  { id: 't-06', objectId: 'obj-005', title: 'Согласование схемы перевода учащихся', assignee: 'Петров И.С.', vedomstvo: 'Минобразования МО', planStart: '2026-06-01', planEnd: '2026-06-30', factStart: '2026-06-05', status: 'in_progress' },
  { id: 't-07', objectId: 'obj-005', title: 'Перевод учащихся в школу № 5', assignee: 'Петров И.С.', vedomstvo: 'Минобразования МО', planStart: '2026-08-26', planEnd: '2026-09-01', status: 'not_started' },
  { id: 't-08', objectId: 'obj-005', title: 'Инвентаризация имущества школы № 7', assignee: 'Лебедева О.В.', vedomstvo: 'Минимущество МО', planStart: '2026-07-20', planEnd: '2026-08-15', status: 'not_started' },
  { id: 't-09', objectId: 'obj-005', title: 'Передача здания на баланс Минимущества МО', assignee: 'Лебедева О.В.', vedomstvo: 'Минимущество МО', planStart: '2026-09-05', planEnd: '2026-09-30', status: 'not_started' },
  // Больница Коломна
  { id: 't-10', objectId: 'obj-010', title: 'Проектная документация и экспертиза', assignee: 'Сидорова Е.М.', vedomstvo: 'Минздрав МО', planStart: '2026-04-01', planEnd: '2026-05-30', factStart: '2026-04-03', factEnd: '2026-06-05', status: 'done' },
  { id: 't-11', objectId: 'obj-010', title: 'Торги и заключение контракта', assignee: 'Смирнова А.В.', vedomstvo: 'Минстрой МО', planStart: '2026-06-01', planEnd: '2026-07-10', factStart: '2026-06-02', status: 'in_progress' },
  { id: 't-12', objectId: 'obj-010', title: 'Ремонтные работы, 1 этап', assignee: 'Волков П.Н.', vedomstvo: 'Минстрой МО', planStart: '2026-07-15', planEnd: '2026-10-30', factStart: '2026-07-15', status: 'in_progress' },
  // Школа № 2, Клин
  { id: 't-13', objectId: 'obj-011', title: 'Проектная документация', assignee: 'Волков П.Н.', vedomstvo: 'Минстрой МО', planStart: '2026-03-06', planEnd: '2026-04-10', factStart: '2026-03-07', factEnd: '2026-04-15', status: 'done' },
  { id: 't-14', objectId: 'obj-011', title: 'Торги и контрактация', assignee: 'Смирнова А.В.', vedomstvo: 'Минстрой МО', planStart: '2026-04-11', planEnd: '2026-05-15', factStart: '2026-04-16', factEnd: '2026-05-18', status: 'done' },
  { id: 't-15', objectId: 'obj-011', title: 'Ремонтные работы', assignee: 'Волков П.Н.', vedomstvo: 'Минстрой МО', planStart: '2026-05-20', planEnd: '2026-07-31', factStart: '2026-05-22', status: 'in_progress' },
  // Поликлиника № 1, Мытищи
  { id: 't-16', objectId: 'obj-012', title: 'Проектная документация и экспертиза', assignee: 'Сидорова Е.М.', vedomstvo: 'Минздрав МО', planStart: '2026-04-03', planEnd: '2026-06-05', factStart: '2026-04-05', factEnd: '2026-06-10', status: 'done' },
  { id: 't-17', objectId: 'obj-012', title: 'Торги и контрактация', assignee: 'Смирнова А.В.', vedomstvo: 'Минстрой МО', planStart: '2026-06-06', planEnd: '2026-07-15', factStart: '2026-06-08', factEnd: '2026-07-14', status: 'done' },
  { id: 't-18', objectId: 'obj-012', title: 'Строительство, 1 этап', assignee: 'Волков П.Н.', vedomstvo: 'Минстрой МО', planStart: '2026-07-16', planEnd: '2026-12-25', factStart: '2026-07-16', status: 'in_progress' },
  // ФОК «Лидер»
  { id: 't-19', objectId: 'obj-014', title: 'Проектирование и экспертиза', assignee: 'Волков П.Н.', vedomstvo: 'Минстрой МО', planStart: '2026-05-11', planEnd: '2026-07-10', factStart: '2026-05-12', factEnd: '2026-07-09', status: 'done' },
  { id: 't-20', objectId: 'obj-014', title: 'Конкурсная документация и торги', assignee: 'Смирнова А.В.', vedomstvo: 'Минстрой МО', planStart: '2026-07-11', planEnd: '2026-08-15', factStart: '2026-07-12', status: 'in_progress' },
  // Школа № 9
  { id: 't-21', objectId: 'obj-015', title: 'Проектная документация', assignee: 'Волков П.Н.', vedomstvo: 'Минстрой МО', planStart: '2026-06-09', planEnd: '2026-06-30', factStart: '2026-06-09', factEnd: '2026-07-02', status: 'done' },
  { id: 't-22', objectId: 'obj-015', title: 'Торги и контрактация', assignee: 'Смирнова А.В.', vedomstvo: 'Минстрой МО', planStart: '2026-07-01', planEnd: '2026-07-25', factStart: '2026-07-03', status: 'in_progress' },
  { id: 't-23', objectId: 'obj-015', title: 'Ремонтные работы', assignee: 'Волков П.Н.', vedomstvo: 'Минстрой МО', planStart: '2026-07-26', planEnd: '2026-08-31', status: 'not_started' },
  // ДК «Родина»
  { id: 't-24', objectId: 'obj-017', title: 'Реставрационный проект', assignee: 'Зайцева Л.Д.', vedomstvo: 'Минкультуры МО', planStart: '2026-07-04', planEnd: '2026-08-20', status: 'not_started' },
  { id: 't-25', objectId: 'obj-017', title: 'Согласование проекта в Минкультуры МО', assignee: 'Зайцева Л.Д.', vedomstvo: 'Минкультуры МО', planStart: '2026-07-04', planEnd: '2026-07-30', factStart: '2026-07-06', status: 'in_progress' },
];

export const DEMO_PROJECTS: Project[] = [
  {
    id: 'prj-1',
    name: 'Реорганизация школьной сети г. Подольска',
    description: 'После завершения капитального ремонта школы № 5 учащиеся школы № 7 переводятся в отремонтированное здание; здание школы № 7 передаётся на баланс Минимущества Московской области.',
    objectIds: ['obj-004', 'obj-005'],
    createdDate: '2026-06-25',
  },
];

export const DEMO_NOTIFICATIONS: NotificationItem[] = [
  { id: 'n-1', date: '2026-07-16T09:12', text: 'Поступил новый объект из ИС «Геопортал МО»: ФАП в д. Никольское', kind: 'object', roles: ['coordinator'], read: false, objectId: 'obj-007' },
  { id: 'n-2', date: '2026-07-15T11:40', text: 'Поступил новый объект из ИС «Геопортал МО»: Школа № 12 на 1224 места', kind: 'object', roles: ['coordinator'], read: false, objectId: 'obj-001' },
  { id: 'n-3', date: '2026-07-13T15:02', text: 'Минкультуры МО завершило проверку по объекту «Дом культуры „Октябрь"»: согласовано', kind: 'check', roles: ['coordinator'], read: true, objectId: 'obj-008' },
  { id: 'n-4', date: '2026-07-10T10:25', text: 'Минздрав МО завершило проверку по объекту «Поликлиника № 3»: согласовано', kind: 'check', roles: ['coordinator'], read: true, objectId: 'obj-003' },
  { id: 'n-5', date: '2026-07-08T08:30', text: 'Назначена проверка по объекту «Поликлиника № 3 — капитальный ремонт»', kind: 'check', roles: ['inspector'], read: false, objectId: 'obj-003' },
  { id: 'n-6', date: '2026-07-01T09:00', text: 'Задача «Согласование схемы перевода учащихся» просрочена (план: 30.06.2026)', kind: 'task', roles: ['inspector', 'manager'], read: false },
  { id: 'n-7', date: '2026-06-30T17:45', text: 'Сформировано итоговое заключение по объекту «Школа № 5»: работы согласованы', kind: 'conclusion', roles: ['manager', 'coordinator'], read: true, objectId: 'obj-004' },
  { id: 'n-8', date: '2026-06-18T12:10', text: 'Итоговое заключение по объекту «Стадион „Труд"»: работы отклонены', kind: 'conclusion', roles: ['manager', 'coordinator'], read: true, objectId: 'obj-006' },
];
